
# Le contexte "events" est obligatoire dans nginx.conf
# Il configure le modèle de gestion des connexions réseau
# worker_connections définit combien de connexions simultanées
# un processus NGINX peut gérer en même temps
events {
	worker_connections 1024;
}

# Le contexte "http" contient toute la configuration web
http {
	# Ces deux directives permettent à NGINX de reconnaître
    # et d'envoyer le bon Content-Type selon l'extension du fichier
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	# Le bloc "server" définit notre serveur virtuel
	server {
		# NGINX écoute sur le port 443 en SSL
        # "ssl" active le chiffrement TLS sur ce port
		listen 443 ssl;
		listen [::]:443 ssl;

		# Le nom de domaine auquel ce serveur répond
		server_name lsadikaj.42.fr;

		# Le certificat SSL et sa clé privée
        # Ces fichiers seront générés par l'entrypoint au démarrage
		ssl_certificate /etc/nginx/ssl/certificate.crt;
		ssl_certificate_key /etc/nginx/ssl/private.key;

		# On autorise uniquement TLSv1.2 et TLSv1.3
		ssl_protocols TLSv1.2 TLSv1.3;

		# Le bloc "location /" gère toutes les requêtes
        # qui ne correspondent pas à un autre bloc location
		location / {
			# try_files essaie de servir la requête dans cet ordre :
            # 1. Un fichier qui correspond exactement à l'URL ($uri)
            # 2. Un dossier qui correspond à l'URL ($uri/)
            # 3. Si rien ne correspond, passe la requête à index.php
            #    avec les paramètres de la requête ($args)
            # C'est le mécanisme qui permet les URLs propres WordPress
            # comme /mon-article au lieu de /?p=42
			try_files $uri $uri/ /index.php?$args;
		}

		# Le bloc "location ~ \.php$" gère toutes les requêtes
        # dont l'URL se termine par .php
        # Le "~" signifie que c'est une expression régulière
		location ~ \.php {
			# Si le fichier PHP n'existe pas, retourne une erreur 404
			try_files $uri = 404;

			# Divise l'URL en deux parties :
            # le chemin du script PHP et les paramètres supplémentaires
			fastcgi_split_path_info ^(.+\.php)(/.+)$;

			# L'adresse de PHP-FPM — "wordpress" est le nom du conteneur
            # Docker le résout vers l'IP du conteneur WordPress
            # via le DNS interne du réseau inception_network
			fastcgi_pass wordpress:9000;

			# Le fichier PHP par défaut si l'URL pointe vers un dossier
			fastcgi_index index.php;

			# Inclut les paramètres FastCGI standard
            # Ce fichier contient les variables d'environnement
            # que PHP-FPM a besoin de recevoir pour traiter la requête
			include fastcgi_params;

			# Indique à PHP-FPM le chemin complet du fichier à exécuter
            # $document_root est la valeur de "root" définie plus haut
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		}
	}
}
