
secrets:
  
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt

services:

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    volumes:
      - db_volume:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception_network
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wp_volume:/var/www/html
    env_file:
      - .env
    secrets:
      - db_password
      - credentials
    networks:
      - inception_network
  
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp_volume:/var/www/html
    networks:
      - inception_network

volumes:
  db_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lsadikaj/data/mariadb

  wp_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lsadikaj/data/wordpress

networks:
  inception_network:
    driver: bridge
